language: java
jdk:
  - openjdk9
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk-ea
  
dist: trusty

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify"

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - rfscholte@apache.org
